// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAKNYa7XRtMBURpApLav12XWGejLwcQP7U',
    appId: '1:28456916844:web:8fd359fc45f1666e2b4549',
    messagingSenderId: '28456916844',
    projectId: 'newsapp-670d2',
    authDomain: 'newsapp-670d2.firebaseapp.com',
    storageBucket: 'newsapp-670d2.appspot.com',
    measurementId: 'G-HBPD31WG2G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBrrM1XGBsKifMCLQ62LajhkxgRRJ39lwA',
    appId: '1:28456916844:android:4bf0a9315166f90d2b4549',
    messagingSenderId: '28456916844',
    projectId: 'newsapp-670d2',
    storageBucket: 'newsapp-670d2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCToc1V-E-HO37CVilAvG9DnxMfF-52Tuw',
    appId: '1:28456916844:ios:124fd7ae98900b3e2b4549',
    messagingSenderId: '28456916844',
    projectId: 'newsapp-670d2',
    storageBucket: 'newsapp-670d2.appspot.com',
    iosBundleId: 'com.shashankfdev.newsApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCToc1V-E-HO37CVilAvG9DnxMfF-52Tuw',
    appId: '1:28456916844:ios:482c9379299e0a042b4549',
    messagingSenderId: '28456916844',
    projectId: 'newsapp-670d2',
    storageBucket: 'newsapp-670d2.appspot.com',
    iosBundleId: 'com.shashankfdev.newsApp.RunnerTests',
  );
}
